Algoritmo "exercicio glicose"

Var
   glicose: real


Inicio
   Escreva ("Digite a medida da glicose: ")
   leia (glicose)


   Se glicose <= 100 entao
      escreval ("Classificação: Normal")
   senao
      se glicose <= 140 entao
         Escreval ("Classificação: Elevado")
      senao
         escreval ("Classificação: Diabetes")
      fimse
   fimse






Fimalgoritmo