Algoritmo "Exercicio pagamento"


Var
   Nome: caracter
   valorHora, HoraTrabalhada, pagamento: real



Inicio

   Escreva ("Nome do funconário: ")
   leia (Nome)
   
   Escreva ("Valor por hora trabalhada: ")
   leia (ValorHora)


   Escreva ("Horas trabalhadas: ")
   leia (HoraTrabalhada)

   pagamento <- ValorHora * HoraTrabalhada

   Escreva ("O pagamento para ",nome," deve ser R$ ", pagamento:4:2)



Fimalgoritmo